server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:todoDb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  banner:
    location: classpath:banner.txt
# TODO Add Profiles For Development and Testing
# TODO Create Docker configuration file
# TODO Create CI pipeline with automated tests
